# Generated by Django 5.2.7 on 2026-10-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0011_delete_langgraphcheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
