# Generated by Django 5.2.7 on 2026-09-23 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webApp', '0026_datasetdocumentationcriterion'),
        ('workflow_engine', '0007_rename_workflow_e_workflo_cached_idx_workflow_en_workflo_88e7a7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Short tagline shown on the sample card', max_length=100)),
                ('pdf_sha256', models.CharField(db_index=True, help_text='Hash of the paper PDF, used to recognise uploads', max_length=64)),
                ('order', models.IntegerField(default=0)),
                ('target_duration_s', models.PositiveIntegerField(default=75, help_text='Replay length of the workflow at 1x speed')),
                ('is_active', models.BooleanField(default=True)),
                ('match_stats', models.JSONField(blank=True, default=dict, help_text='Evidence-matching dry run from prepare_demo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_scenarios', to='webApp.paper')),
                ('workflow_run', models.ForeignKey(help_text='Completed run whose node timings, logs and results are replayed', on_delete=django.db.models.deletion.CASCADE, related_name='demo_scenarios', to='workflow_engine.workflowrun')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
